version: "3"

services:
  uploader-webserver:
    image: nginx:mainline-alpine
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    container_name: uploader-webserver
    depends_on:
      - uploader-api
      - uploader-client
    networks:
      - uploader-network
  uploader-api:
    image: sykeben/file-uploader-api:1.x
    environment:
      - DEFAULT_DIR=/files
      - MAX_SIZE_MB=2048
      - CLEAN_ENABLED=true
    container_name: uploader-backend
    volumes:
      - file_storage:/files
    restart: unless-stopped
    networks:
      - uploader-network
  uploader-client:
    image: sykeben/file-uploader-client:1.x
    container_name: uploader-frontend
    restart: unless-stopped
    networks:
      - uploader-network

volumes:
  file_storage:

networks:
  uploader-network:
    driver: bridge
