version: "3"

services:
  webserver:
    container_name: webserver
    image: nginx:mainline-alpine
    volumes:
      - web-root:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - site-network
  backend:
    image: sykeben/file-uploader-api:latest
    environment:
      - DEFAULT_DIR=/files
      - RANDOMIZE_FILENAMES=true
      - SHARE_ENABLED=true
      - MAX_SIZE_MB=2048
    container_name: backend
    volumes:
      - /media/files:/files
    restart: unless-stopped
    networks:
      - site-network
  frontend:
    image: sykeben/file-uploader-client:latest
    container_name: frontend
    restart: unless-stopped
    networks:
      - site-network

volumes:
  web-root:
    driver: local

networks:
  site-network:
    driver: bridge